wandb_version: 1

file:
  desc: null
  value: light_heavy_word2vec.dill
_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694766501.197433
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.1
      5: 0.15.10
      8:
      - 3
      - 5
